### ISSUE TITLE
inconsistency in Text

### ISSUE THREAD

**Issue by Saurav-Pant** [vivekrawat21/Fitness-web-app#11]
![what](https://github.com/vivekrawat21/Fitness-web-app/assets/103263909/a7b3e296-c5dc-4e03-8dda-c34fb15b0862)
Here, This is not visible fully and in the dark mode it's not looking cool, If you think so, tell me

**Comment by vivekrawat21** [comment]
if not looking good then ok change it

**Comment by Saurav-Pant** [comment]
Thanks, I will work on it
